[package]
name = "api-parser"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]

[dependencies]
pest = "^1.0"
pest_derive = "^1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
