[package]
name = "plugin-manager"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]

[dependencies]
libloading = "0.5.0"
log = "0.4"
error-chain = "~0.12.0"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }