[package]
name = "api-analyzer"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]

[dependencies]
api-parser = { path = "../api-parser", version = "*" }
serde = "1.0"
serde_derive = "1.0"
